.PHONY: help

race:
	go test -race -v -run Test_Race_ ./

help:
	@echo "Usage: make [target]"
	@echo "This Makefile contains targets to test and build a Go program."
	@echo "It contains the following targets:"
	@echo
	@echo "  rece   - race detect"
	@echo